# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-12 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('feedbackcontent', models.TextField()),
            ],
        ),
    ]
