# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-23 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('webID', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField()),
                ('link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('organiser', models.CharField(blank=True, max_length=50, null=True)),
                ('organiser_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organiser_phone', models.BigIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('online', models.NullBooleanField(default='True')),
                ('ppool', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='warehouse.Event')),
                ('meetup_id', models.CharField(max_length=30)),
            ],
            bases=('warehouse.event',),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Cities'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.EventType'),
        ),
    ]
