# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-01 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20180101_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
