# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-01 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20180101_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='organiser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
