# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-01 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_auto_20180101_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='organiser',
            field=models.TextField(blank=True, null=True),
        ),
    ]
