# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-03 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_auto_20180101_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img_url',
            field=models.URLField(default='NA'),
        ),
    ]
