# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-20 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_auto_20180109_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbid', models.BigIntegerField()),
                ('log_type', models.CharField(max_length=10)),
                ('value', models.TextField()),
                ('log_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
