# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-20 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutsideClicks',
            fields=[
                ('who', models.BigIntegerField(primary_key=True, serialize=False)),
                ('where', models.URLField()),
                ('when', models.DateTimeField()),
            ],
        ),
    ]
